version: '3.1'
services:
  mongo:
    image: mongo:4.2.5
    environment: 
      MONGO_INITDB_ROOT_USERNAME: zipcode
      MONGO_INITDB_ROOT_PASSWORD: zipcode
      MONGO_INITDB_DATABASE: zipcode
    ports:
      - 27017:27017
  zipcode:
    image: felipefrizzo/brazilian-zipcode-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment: 
      MONGO_URI: "mongodb://zipcode:zipcode@mongo:27017/admin"
    ports:
      - 8000:8000